name: Deploy Bot to Hetzner VPS

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - master  # Or master, or whichever branch you use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a standard GitHub runner
    # runs-on: ubuntu-latest-large

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to get your repository code

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
           # Copy everything (you can specify src folders like "src/*" if needed)
          source: "./."
          target: ${{ secrets.BOT_DIR }}

      # Step 2: Run update and restart commands on the VPS
      - name: Update Dependencies and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            echo "Executing commands in target directory: ${{ secrets.BOT_DIR }}"
            cd ${{ secrets.BOT_DIR }}

            echo "Updating Python dependencies..."
            # Activate virtual environment using the path from secrets
            source ${{ secrets.VENV_PATH }}/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            echo "Restarting the discord-music-bot service via systemd..."
            # Use sudo because systemctl requires root privileges
            # Ensure 'music_bot.service' matches the filename you created
            sudo systemctl restart music_bot.service 
            sudo systemctl restart intro_bot.service 

            # Optional: Add a small delay and check status
            sleep 40
            
            echo "Checking service status (output below):"
            sudo systemctl status music_bot.service --no-pager
            
            echo "Checking discord-intro-bot status (output below):"
            sudo systemctl status intro_bot.service --no-pager

            echo "Deployment steps complete."